// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fa_proto_msg.proto

package com.jylee.serial.protobuf;

public final class FaProtoMsg {
  private FaProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FAMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string fa_id = 1;
    /**
     * <code>required string fa_id = 1;</code>
     */
    boolean hasFaId();
    /**
     * <code>required string fa_id = 1;</code>
     */
    java.lang.String getFaId();
    /**
     * <code>required string fa_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getFaIdBytes();

    // required .com.jylee.serial.protobuf.FAMsg.Status status = 2;
    /**
     * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
     */
    com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status getStatus();

    // required string kind = 3;
    /**
     * <code>required string kind = 3;</code>
     */
    boolean hasKind();
    /**
     * <code>required string kind = 3;</code>
     */
    java.lang.String getKind();
    /**
     * <code>required string kind = 3;</code>
     */
    com.google.protobuf.ByteString
        getKindBytes();

    // required string command = 4;
    /**
     * <code>required string command = 4;</code>
     */
    boolean hasCommand();
    /**
     * <code>required string command = 4;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>required string command = 4;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();

    // required string msg_id = 5;
    /**
     * <code>required string msg_id = 5;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required string msg_id = 5;</code>
     */
    java.lang.String getMsgId();
    /**
     * <code>required string msg_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    // repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    java.util.List<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV> 
        getParamsList();
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV getParams(int index);
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    java.util.List<? extends com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder> 
        getParamsOrBuilderList();
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder getParamsOrBuilder(
        int index);

    // optional string body = 7;
    /**
     * <code>optional string body = 7;</code>
     */
    boolean hasBody();
    /**
     * <code>optional string body = 7;</code>
     */
    java.lang.String getBody();
    /**
     * <code>optional string body = 7;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code com.jylee.serial.protobuf.FAMsg}
   */
  public static final class FAMsg extends
      com.google.protobuf.GeneratedMessage
      implements FAMsgOrBuilder {
    // Use FAMsg.newBuilder() to construct.
    private FAMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FAMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FAMsg defaultInstance;
    public static FAMsg getDefaultInstance() {
      return defaultInstance;
    }

    public FAMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FAMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              faId_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status value = com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              kind_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              command_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msgId_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                params_ = new java.util.ArrayList<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV>();
                mutable_bitField0_ |= 0x00000020;
              }
              params_.add(input.readMessage(com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.PARSER, extensionRegistry));
              break;
            }
            case 58: {
              bitField0_ |= 0x00000020;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jylee.serial.protobuf.FaProtoMsg.FAMsg.class, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<FAMsg> PARSER =
        new com.google.protobuf.AbstractParser<FAMsg>() {
      public FAMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FAMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FAMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.jylee.serial.protobuf.FAMsg.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQ = 1;</code>
       */
      REQ(0, 1),
      /**
       * <code>SUCC = 2;</code>
       */
      SUCC(1, 2),
      /**
       * <code>FAIL = 3;</code>
       */
      FAIL(2, 3),
      /**
       * <code>ERROR = 4;</code>
       */
      ERROR(3, 4),
      /**
       * <code>UNKNOWN = 5;</code>
       */
      UNKNOWN(4, 5),
      ;

      /**
       * <code>REQ = 1;</code>
       */
      public static final int REQ_VALUE = 1;
      /**
       * <code>SUCC = 2;</code>
       */
      public static final int SUCC_VALUE = 2;
      /**
       * <code>FAIL = 3;</code>
       */
      public static final int FAIL_VALUE = 3;
      /**
       * <code>ERROR = 4;</code>
       */
      public static final int ERROR_VALUE = 4;
      /**
       * <code>UNKNOWN = 5;</code>
       */
      public static final int UNKNOWN_VALUE = 5;


      public final int getNumber() { return value; }

      public static Status valueOf(int value) {
        switch (value) {
          case 1: return REQ;
          case 2: return SUCC;
          case 3: return FAIL;
          case 4: return ERROR;
          case 5: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.jylee.serial.protobuf.FAMsg.Status)
    }

    public interface KVOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string key = 1;
      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // required string value = 2;
      /**
       * <code>required string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>required string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();

      // optional string info = 3;
      /**
       * <code>optional string info = 3;</code>
       */
      boolean hasInfo();
      /**
       * <code>optional string info = 3;</code>
       */
      java.lang.String getInfo();
      /**
       * <code>optional string info = 3;</code>
       */
      com.google.protobuf.ByteString
          getInfoBytes();
    }
    /**
     * Protobuf type {@code com.jylee.serial.protobuf.FAMsg.KV}
     */
    public static final class KV extends
        com.google.protobuf.GeneratedMessage
        implements KVOrBuilder {
      // Use KV.newBuilder() to construct.
      private KV(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private KV(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final KV defaultInstance;
      public static KV getDefaultInstance() {
        return defaultInstance;
      }

      public KV getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private KV(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                info_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_KV_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_KV_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.class, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder.class);
      }

      public static com.google.protobuf.Parser<KV> PARSER =
          new com.google.protobuf.AbstractParser<KV>() {
        public KV parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new KV(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<KV> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string info = 3;
      public static final int INFO_FIELD_NUMBER = 3;
      private java.lang.Object info_;
      /**
       * <code>optional string info = 3;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            info_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
        info_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getInfoBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getInfoBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.jylee.serial.protobuf.FAMsg.KV}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_KV_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_KV_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.class, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder.class);
        }

        // Construct using com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          info_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_KV_descriptor;
        }

        public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV getDefaultInstanceForType() {
          return com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.getDefaultInstance();
        }

        public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV build() {
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV buildPartial() {
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV result = new com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.info_ = info_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV) {
            return mergeFrom((com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV other) {
          if (other == com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          if (other.hasInfo()) {
            bitField0_ |= 0x00000004;
            info_ = other.info_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // required string value = 2;
        private java.lang.Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // optional string info = 3;
        private java.lang.Object info_ = "";
        /**
         * <code>optional string info = 3;</code>
         */
        public boolean hasInfo() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string info = 3;</code>
         */
        public java.lang.String getInfo() {
          java.lang.Object ref = info_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            info_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string info = 3;</code>
         */
        public com.google.protobuf.ByteString
            getInfoBytes() {
          java.lang.Object ref = info_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            info_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string info = 3;</code>
         */
        public Builder setInfo(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          info_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string info = 3;</code>
         */
        public Builder clearInfo() {
          bitField0_ = (bitField0_ & ~0x00000004);
          info_ = getDefaultInstance().getInfo();
          onChanged();
          return this;
        }
        /**
         * <code>optional string info = 3;</code>
         */
        public Builder setInfoBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          info_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.jylee.serial.protobuf.FAMsg.KV)
      }

      static {
        defaultInstance = new KV(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.jylee.serial.protobuf.FAMsg.KV)
    }

    private int bitField0_;
    // required string fa_id = 1;
    public static final int FA_ID_FIELD_NUMBER = 1;
    private java.lang.Object faId_;
    /**
     * <code>required string fa_id = 1;</code>
     */
    public boolean hasFaId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fa_id = 1;</code>
     */
    public java.lang.String getFaId() {
      java.lang.Object ref = faId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          faId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fa_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFaIdBytes() {
      java.lang.Object ref = faId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.jylee.serial.protobuf.FAMsg.Status status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status status_;
    /**
     * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
     */
    public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status getStatus() {
      return status_;
    }

    // required string kind = 3;
    public static final int KIND_FIELD_NUMBER = 3;
    private java.lang.Object kind_;
    /**
     * <code>required string kind = 3;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string kind = 3;</code>
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          kind_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string kind = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string command = 4;
    public static final int COMMAND_FIELD_NUMBER = 4;
    private java.lang.Object command_;
    /**
     * <code>required string command = 4;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string command = 4;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          command_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string command = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string msg_id = 5;
    public static final int MSG_ID_FIELD_NUMBER = 5;
    private java.lang.Object msgId_;
    /**
     * <code>required string msg_id = 5;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string msg_id = 5;</code>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;
    public static final int PARAMS_FIELD_NUMBER = 6;
    private java.util.List<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV> params_;
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    public java.util.List<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV> getParamsList() {
      return params_;
    }
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    public java.util.List<? extends com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder> 
        getParamsOrBuilderList() {
      return params_;
    }
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
     */
    public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder getParamsOrBuilder(
        int index) {
      return params_.get(index);
    }

    // optional string body = 7;
    public static final int BODY_FIELD_NUMBER = 7;
    private java.lang.Object body_;
    /**
     * <code>optional string body = 7;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string body = 7;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string body = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      faId_ = "";
      status_ = com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status.REQ;
      kind_ = "";
      command_ = "";
      msgId_ = "";
      params_ = java.util.Collections.emptyList();
      body_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFaId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getParamsCount(); i++) {
        if (!getParams(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFaIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getKindBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCommandBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgIdBytes());
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeMessage(6, params_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getBodyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFaIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getKindBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCommandBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgIdBytes());
      }
      for (int i = 0; i < params_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, params_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getBodyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jylee.serial.protobuf.FaProtoMsg.FAMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jylee.serial.protobuf.FaProtoMsg.FAMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jylee.serial.protobuf.FAMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jylee.serial.protobuf.FaProtoMsg.FAMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jylee.serial.protobuf.FaProtoMsg.FAMsg.class, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Builder.class);
      }

      // Construct using com.jylee.serial.protobuf.FaProtoMsg.FAMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParamsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        faId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status.REQ;
        bitField0_ = (bitField0_ & ~0x00000002);
        kind_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          paramsBuilder_.clear();
        }
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jylee.serial.protobuf.FaProtoMsg.internal_static_com_jylee_serial_protobuf_FAMsg_descriptor;
      }

      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg getDefaultInstanceForType() {
        return com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance();
      }

      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg build() {
        com.jylee.serial.protobuf.FaProtoMsg.FAMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg buildPartial() {
        com.jylee.serial.protobuf.FaProtoMsg.FAMsg result = new com.jylee.serial.protobuf.FaProtoMsg.FAMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.faId_ = faId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgId_ = msgId_;
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            params_ = java.util.Collections.unmodifiableList(params_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jylee.serial.protobuf.FaProtoMsg.FAMsg) {
          return mergeFrom((com.jylee.serial.protobuf.FaProtoMsg.FAMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jylee.serial.protobuf.FaProtoMsg.FAMsg other) {
        if (other == com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance()) return this;
        if (other.hasFaId()) {
          bitField0_ |= 0x00000001;
          faId_ = other.faId_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasKind()) {
          bitField0_ |= 0x00000004;
          kind_ = other.kind_;
          onChanged();
        }
        if (other.hasCommand()) {
          bitField0_ |= 0x00000008;
          command_ = other.command_;
          onChanged();
        }
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000010;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (paramsBuilder_ == null) {
          if (!other.params_.isEmpty()) {
            if (params_.isEmpty()) {
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureParamsIsMutable();
              params_.addAll(other.params_);
            }
            onChanged();
          }
        } else {
          if (!other.params_.isEmpty()) {
            if (paramsBuilder_.isEmpty()) {
              paramsBuilder_.dispose();
              paramsBuilder_ = null;
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000020);
              paramsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParamsFieldBuilder() : null;
            } else {
              paramsBuilder_.addAllMessages(other.params_);
            }
          }
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000040;
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFaId()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasKind()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasMsgId()) {
          
          return false;
        }
        for (int i = 0; i < getParamsCount(); i++) {
          if (!getParams(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jylee.serial.protobuf.FaProtoMsg.FAMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jylee.serial.protobuf.FaProtoMsg.FAMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string fa_id = 1;
      private java.lang.Object faId_ = "";
      /**
       * <code>required string fa_id = 1;</code>
       */
      public boolean hasFaId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fa_id = 1;</code>
       */
      public java.lang.String getFaId() {
        java.lang.Object ref = faId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          faId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fa_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFaIdBytes() {
        java.lang.Object ref = faId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fa_id = 1;</code>
       */
      public Builder setFaId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        faId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fa_id = 1;</code>
       */
      public Builder clearFaId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        faId_ = getDefaultInstance().getFaId();
        onChanged();
        return this;
      }
      /**
       * <code>required string fa_id = 1;</code>
       */
      public Builder setFaIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        faId_ = value;
        onChanged();
        return this;
      }

      // required .com.jylee.serial.protobuf.FAMsg.Status status = 2;
      private com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status status_ = com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status.REQ;
      /**
       * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
       */
      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status getStatus() {
        return status_;
      }
      /**
       * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
       */
      public Builder setStatus(com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.jylee.serial.protobuf.FAMsg.Status status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.jylee.serial.protobuf.FaProtoMsg.FAMsg.Status.REQ;
        onChanged();
        return this;
      }

      // required string kind = 3;
      private java.lang.Object kind_ = "";
      /**
       * <code>required string kind = 3;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string kind = 3;</code>
       */
      public java.lang.String getKind() {
        java.lang.Object ref = kind_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          kind_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string kind = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKindBytes() {
        java.lang.Object ref = kind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string kind = 3;</code>
       */
      public Builder setKind(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string kind = 3;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000004);
        kind_ = getDefaultInstance().getKind();
        onChanged();
        return this;
      }
      /**
       * <code>required string kind = 3;</code>
       */
      public Builder setKindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        kind_ = value;
        onChanged();
        return this;
      }

      // required string command = 4;
      private java.lang.Object command_ = "";
      /**
       * <code>required string command = 4;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string command = 4;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string command = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string command = 4;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 4;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000008);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 4;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        command_ = value;
        onChanged();
        return this;
      }

      // required string msg_id = 5;
      private java.lang.Object msgId_ = "";
      /**
       * <code>required string msg_id = 5;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string msg_id = 5;</code>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg_id = 5;</code>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg_id = 5;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg_id = 5;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgId_ = value;
        onChanged();
        return this;
      }

      // repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;
      private java.util.List<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV> params_ =
        java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          params_ = new java.util.ArrayList<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV>(params_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder> paramsBuilder_;

      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public java.util.List<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV> getParamsList() {
        if (paramsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(params_);
        } else {
          return paramsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public int getParamsCount() {
        if (paramsBuilder_ == null) {
          return params_.size();
        } else {
          return paramsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV getParams(int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);
        } else {
          return paramsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder setParams(
          int index, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.set(index, value);
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder setParams(
          int index, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder addParams(com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder addParams(
          int index, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(index, value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder addParams(
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder addParams(
          int index, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV> values) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          super.addAll(values, params_);
          onChanged();
        } else {
          paramsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public Builder removeParams(int index) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.remove(index);
          onChanged();
        } else {
          paramsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder getParamsBuilder(
          int index) {
        return getParamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder getParamsOrBuilder(
          int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);  } else {
          return paramsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public java.util.List<? extends com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder> 
           getParamsOrBuilderList() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(params_);
        }
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder addParamsBuilder() {
        return getParamsFieldBuilder().addBuilder(
            com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.getDefaultInstance());
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder addParamsBuilder(
          int index) {
        return getParamsFieldBuilder().addBuilder(
            index, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.getDefaultInstance());
      }
      /**
       * <code>repeated .com.jylee.serial.protobuf.FAMsg.KV params = 6;</code>
       */
      public java.util.List<com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder> 
           getParamsBuilderList() {
        return getParamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KV.Builder, com.jylee.serial.protobuf.FaProtoMsg.FAMsg.KVOrBuilder>(
                  params_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      // optional string body = 7;
      private java.lang.Object body_ = "";
      /**
       * <code>optional string body = 7;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000040);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 7;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        body_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jylee.serial.protobuf.FAMsg)
    }

    static {
      defaultInstance = new FAMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jylee.serial.protobuf.FAMsg)
  }

  /**
   * Protobuf service {@code com.jylee.serial.protobuf.FAService}
   */
  public static abstract class FAService
      implements com.google.protobuf.Service {
    protected FAService() {}

    public interface Interface {
      /**
       * <code>rpc Append(.com.jylee.serial.protobuf.FAMsg) returns (.com.jylee.serial.protobuf.FAMsg);</code>
       */
      public abstract void append(
          com.google.protobuf.RpcController controller,
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg request,
          com.google.protobuf.RpcCallback<com.jylee.serial.protobuf.FaProtoMsg.FAMsg> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new FAService() {
        @java.lang.Override
        public  void append(
            com.google.protobuf.RpcController controller,
            com.jylee.serial.protobuf.FaProtoMsg.FAMsg request,
            com.google.protobuf.RpcCallback<com.jylee.serial.protobuf.FaProtoMsg.FAMsg> done) {
          impl.append(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.append(controller, (com.jylee.serial.protobuf.FaProtoMsg.FAMsg)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Append(.com.jylee.serial.protobuf.FAMsg) returns (.com.jylee.serial.protobuf.FAMsg);</code>
     */
    public abstract void append(
        com.google.protobuf.RpcController controller,
        com.jylee.serial.protobuf.FaProtoMsg.FAMsg request,
        com.google.protobuf.RpcCallback<com.jylee.serial.protobuf.FaProtoMsg.FAMsg> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.jylee.serial.protobuf.FaProtoMsg.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.append(controller, (com.jylee.serial.protobuf.FaProtoMsg.FAMsg)request,
            com.google.protobuf.RpcUtil.<com.jylee.serial.protobuf.FaProtoMsg.FAMsg>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.jylee.serial.protobuf.FaProtoMsg.FAService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void append(
          com.google.protobuf.RpcController controller,
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg request,
          com.google.protobuf.RpcCallback<com.jylee.serial.protobuf.FaProtoMsg.FAMsg> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.jylee.serial.protobuf.FaProtoMsg.FAMsg.class,
            com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg append(
          com.google.protobuf.RpcController controller,
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.jylee.serial.protobuf.FaProtoMsg.FAMsg append(
          com.google.protobuf.RpcController controller,
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg request)
          throws com.google.protobuf.ServiceException {
        return (com.jylee.serial.protobuf.FaProtoMsg.FAMsg) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.jylee.serial.protobuf.FaProtoMsg.FAMsg.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.jylee.serial.protobuf.FAService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jylee_serial_protobuf_FAMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jylee_serial_protobuf_FAMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jylee_serial_protobuf_FAMsg_KV_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jylee_serial_protobuf_FAMsg_KV_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022fa_proto_msg.proto\022\027com.jylee.serial.pro" +
      "tobuf\"\254\002\n\005FAMsg\022\r\n\005fa_id\030\001 \002(\t\0225\n\006status" +
      "\030\002 \002(\0162%.com.jylee.serial.protobuf.FAMsg.S" +
      "tatus\022\014\n\004kind\030\003 \002(\t\022\017\n\007command\030\004 \002(\t\022\016\n\006" +
      "msg_id\030\005 \002(\t\0221\n\006params\030\006 \003(\0132!.com.jylee.s" +
      "erial.protobuf.FAMsg.KV\022\014\n\004body\030\007 \001(\t\032.\n" +
      "\002KV\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\022\014\n\004info\030" +
      "\003 \001(\t\"=\n\006Status\022\007\n\003REQ\020\001\022\010\n\004SUCC\020\002\022\010\n\004FA" +
      "IL\020\003\022\t\n\005ERROR\020\004\022\013\n\007UNKNOWN\020\0052U\n\tFAServic" +
      "e\022H\n\006Append\022\036.com.jylee.serial.protobuf.FA",
      "Msg\032\036.com.jylee.serial.protobuf.FAMsgB\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_jylee_serial_protobuf_FAMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_jylee_serial_protobuf_FAMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_jylee_serial_protobuf_FAMsg_descriptor,
              new java.lang.String[] { "FaId", "Status", "Kind", "Command", "MsgId", "Params", "Body", });
          internal_static_com_jylee_serial_protobuf_FAMsg_KV_descriptor =
            internal_static_com_jylee_serial_protobuf_FAMsg_descriptor.getNestedTypes().get(0);
          internal_static_com_jylee_serial_protobuf_FAMsg_KV_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_jylee_serial_protobuf_FAMsg_KV_descriptor,
              new java.lang.String[] { "Key", "Value", "Info", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
