#!/bin/sh

### BEGIN INIT INFO
# Provides: authcastle
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# chkconfig: - 99 99
# Short-Description: start and stop authcastle
# Description: Start, stop and save authcastle
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

get_instdir()
{
	if [ -f $CONF_FILE -a -r $CONF_FILE ] ; then
		AC_HOME=`cat $CONF_FILE | grep -v "#" | grep AC_HOME | awk -F= '{print $2 }' | sed -e 's/^[ \t]*//'`
	else
		echo "[ERROR] AuthCastle is not installed. $CONF_FILE not found."
		exit 1
	fi

	if [ -d $AC_HOME ] ; then
		AC_HOME=$AC_HOME
	else
		echo "[ERROR] not installed1."
	fi
}

CONF_FILE=/etc/authcastle.conf

#AC_HOME=/usr/local/authcastle

get_instdir

prog=acbackup
#AC_USER=acuser
AC_USER=root

# jsvc path
JSVC=$AC_HOME/bin/jsvc

#JAVA_HOME=/usr/lib/jvm/jre-1.6.0-openjdk.x86_64
JAVA_HOME=$AC_HOME/bin/jre1.8.0_60

# conf
ACD_LIBDIR=$AC_HOME/acbackup/lib
ACD_PID=$AC_HOME/bin/acbackup-pid
ACD_OUT=$AC_HOME/logs/acbackup-stdout.log
ACD_ERR=$AC_HOME/logs/acbackup-stderr.log

ACBACKUP_MAIN=sga.sol.ac.acbackup.daemon.handler.DaemonHandler
JSVC_OPTS="-DAC_HOME=$AC_HOME"

CLASSPATH=`(echo $ACD_LIBDIR/*.jar|tr ' ' ':')`
CLASSPATH=$AC_HOME:$AC_HOME/acbackup:$AC_HOME/acbackup/acbackup-daemon.jar:$CLASSPATH

#echo classpath: "$CLASSPATH"
#	-debug -verbose:class \

start() {
	echo -n $"Starting $prog: "

	if [ ! -e "$AC_HOME"/logs ]; then
		mkdir "$AC_HOME"/logs
	fi

	"$JSVC" \
	-user "$AC_USER" \
	-pidfile "$ACD_PID" \
	-outfile "$ACD_OUT" \
	-errfile "$ACD_ERR" \
	-java-home "$JAVA_HOME" \
	-classpath "$CLASSPATH" \
	-procname "$prog" \
	-DAC_HOME="$AC_HOME" \
	"$ACBACKUP_MAIN"

	[ $? -eq 0 ] && success || failure;
	echo
}

stop() {
	echo -n $"Stopping $prog: "

	"$JSVC" \
	-stop \
	-pidfile "$ACD_PID" \
	-procname "acbackup" \
	"$ACBACKUP_MAIN"

	[ $? -eq 0 ] && success || failure;
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status -p $ACD_PID $prog
		;;
esac
